### ISSUE TITLE
Incomplete autoconf's changes for source code dir move: src -> usbfluxd

### ISSUE THREAD

**Issue by sferrini** [corellium/usbfluxd#1]
Autoconf's [configure.ac](https://github.com/corellium/usbfluxd/blob/8c4ecc14d5d6a1163f78a2c60f842eef00c1c45d/configure.ac#L8) file points `AC_CONFIG_SRCDIR` to `src/` but the source code has been [recently moved](https://github.com/corellium/usbfluxd/commit/2951cc3081b8b36209decf655f09d5089e09d267) to `usbfluxd/`.

I fixed the compilation errors creating a symlink, but I guess is more appropriate to change `AC_CONFIG_SRCDIR` and the various hardcoded paths (in makedmg.sh, Xcode project, etc) accordingly.

**Comment by cmwdotme** [comment]
Thanks
